### ISSUE TITLE
Correct Property objects

### ISSUE THREAD

**Issue by gaurav21r** [super-elements/super-grid#1]
@lakshay1994 I can see other properties as `type: "boolean"`, but you've rightly made them as `type: Boolean`. Mind correcting the others?,

Also please read https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-reflection

We need to do `<super-grid tree="true" selection="true" remove-header>` Although your example may work, I think we need to include `reflectToAttribute` so that programmatic changes to the DOM will turn this **attribute** on or off.

Finally, also see https://github.com/super-elements/super-grid/commit/808eb3411aa4d2bdcfcc12aa086a16f84c0dc9a5#commitcomment-15946700

**Comment by lakshay1994** [comment]
ok sure

**Comment by gaurav21r** [comment]
Looks good, I'll test tomo and close this :+1:
