### ISSUE TITLE
when we change the value of nested objects, the change is not reflected on the `iron-list`.

### ISSUE THREAD

**Issue by shljk** [super-elements/super-grid#7]
Items = [ { name: 'xyz',
            age:   '23',
            address: [ { address1: { street : 'skt',
                                     city: 'DLI',
                                     pincode: '0000000'
                                   },
                     } ],
           },
           { name: 'abc',
             age:   '90',
             address: [ { address1: { street : '420',
                                      city: 'LKO',
                                      pincode: '0000001'
                                    },
                      } ],
          } ] 
when we want to change the nested object from  items JSON of `iron-list` . It's not working.
For example: 
I want to replace the age'23' to age '30'.
Items = [ { name: 'xyz',
            age:   '30',
            address: [ { address1: { street : 'skt',
                                     city: 'DLI',
                                     pincode: '0000000'
                                   },
                     } ],
           },
           { name: 'zzzz',
             age:   '90',
             address: [ { address1: { street : '420',
                                      city: 'LKO',
                                      pincode: '0000001'
                                    },
                      } ],
          } ]

**Comment by gaurav21r** [comment]
@shljk Please add a comment to #6
